<a href="https://colab.research.google.com/github/SAMAWELJABALLI/intro_to_keras/blob/master/wine_red_or_white.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


In [2]:
df_red = pd.read_csv('/content/winequality-red.csv', sep=';')
df_white = pd.read_csv('/content/winequality-white.csv', sep=';')

In [3]:
df_red.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [4]:
df_white.head()


fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.0              0.27         0.36  ...       0.45      8.8        6
1            6.3              0.30         0.34  ...       0.49      9.5        6
2            8.1              0.28         0.40  ...       0.44     10.1        6
3            7.2              0.23         0.32  ...       0.40      9.9        6
4            7.2              0.23         0.32  ...       0.40      9.9        6

[5 rows x 12 columns]

In [5]:
df_red.shape

(1599, 12)

In [6]:
df_white.shape

(4898, 12)

In [7]:
df_red.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [8]:
df_white.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


In [9]:
pd.isnull(df_red).sum()


fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [10]:
pd.isnull(df_white).sum()


fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [12]:
# 1 = red
# 0 - white
df_red['type'] = 1
df_white['type'] = 0

In [15]:
df_red.columns


Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'type'],
      dtype='object')

In [16]:
df_white.columns


Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'type'],
      dtype='object')

In [17]:
df = pd.concat([df_red, df_white], ignore_index=True)

In [19]:
df.head()

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  type
0            7.4              0.70         0.00  ...      9.4        5     1
1            7.8              0.88         0.00  ...      9.8        5     1
2            7.8              0.76         0.04  ...      9.8        5     1
3           11.2              0.28         0.56  ...      9.8        6     1
4            7.4              0.70         0.00  ...      9.4        5     1

[5 rows x 13 columns]

In [20]:
df.tail()

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  type
6492            6.2              0.21         0.29  ...     11.2        6     0
6493            6.6              0.32         0.36  ...      9.6        5     0
6494            6.5              0.24         0.19  ...      9.4        6     0
6495            5.5              0.29         0.30  ...     12.8        7     0
6496            6.0              0.21         0.38  ...     11.8        6     0

[5 rows x 13 columns]

In [21]:
df.shape

(6497, 13)

In [22]:
X = df.drop(columns=['type'])
y = df['type']

In [23]:
X.shape

(6497, 12)

In [24]:
y.shape

(6497,)

In [25]:
#Split Data into training and test¶
from sklearn.model_selection import train_test_split

# Note the use of stratify=y
# where 'y' is the NOT for yes, but the actual variable 'y' that contains the target
# stratify=y will make sure the training and test data has the same percentage of each target so we 
# do not get a skewed dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, stratify=y)

In [26]:
y.sum()/y.count()


0.2461135908881022

In [27]:
y_train.sum()/y_train.count()

0.24609375

In [28]:
y_test.sum()/y_test.count()

0.24615384615384617

In [29]:
X_train.shape

(4352, 12)

In [30]:
X_test.shape

(2145, 12)

In [31]:
y_test.sum()

528

In [32]:
y_train.sum(
)

1071

In [33]:
#Standardize Dataset
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [34]:
X_train.head()


fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
5025            7.1             0.170         0.40  ...       0.78     9.10        6
2238            5.8             0.335         0.14  ...       0.71    10.30        5
4834            5.7             0.150         0.28  ...       0.27    11.20        6
6143            5.8             0.280         0.30  ...       0.58    12.75        6
2892            6.9             0.390         0.22  ...       0.87    11.60        4

[5 rows x 12 columns]

In [37]:
df_train_scaled = pd.DataFrame(X_train_scaled)
df_train_scaled.head()


0         1         2   ...        9         10        11
0 -0.082151 -1.016338  0.557545  ...  1.689005 -1.171387  0.190425
1 -1.076653 -0.025627 -1.235015  ...  1.213826 -0.166457 -0.954228
2 -1.153153 -1.136424 -0.269790  ... -1.773017  0.587241  0.190425
3 -1.076653 -0.355864 -0.131901  ...  0.331350  1.885275  0.190425
4 -0.235152  0.304610 -0.683458  ...  2.299950  0.922217 -2.098881

[5 rows x 12 columns]

SyntaxError: ignored


**Create Keras Model Architecture - Single Output Node**

In [39]:
from keras.models import Sequential, load_model
from keras.layers import Dense
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score, classification_report

In [42]:

# The input_shape is needed in the input layer to tell Keras how many input features to expect
input_shape = X_train_scaled.shape[1]
print(input_shape)

12


In [43]:
#Create Keras Model
model = Sequential()

# Add the first layer
model.add(Dense(12, activation='relu', input_shape=(input_shape,)))

# Add the second layer
model.add(Dense(8, activation='relu'))

# Add the output layer
# activation = sigmoid gives probabilities as predicted outputs
model.add(Dense(1,activation='sigmoid'))

# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [50]:
# fit will perform the backpropagation and gradient descent
# fit(X_train, y_train)
model.fit(X_train_scaled, y_train, epochs=100, validation_split=0.4, batch_size=64, verbose=0)

In [51]:
y_pred = model.predict(X_test_scaled)

In [52]:
y_pred[:5]

array([[4.4128145e-05],
       [9.9677050e-01],
       [2.3832310e-07],
       [1.0000000e+00],
       [4.2524934e-04]], dtype=float32)

In [59]:
# for this, lets assume any probability above 0.5, means Red wine
cm = confusion_matrix(y_test, y_pred >= 0.5)
df_cm = pd.DataFrame(
        cm, index=['white', 'red'], columns=['white', 'red'], 
    )
df_cm.head()

white  red
white   1613    4
red        5  523

In [60]:
score = model.evaluate(X_test_scaled, y_test,verbose=1)
print(f'Loss: {score[0]}, Accuracy: {score[1]}')


68/68 [==============================] - 0s 1ms/step - loss: 0.0234 - accuracy: 0.9958
Loss: 0.023412249982357025, Accuracy: 0.9958041906356812


**Create Keras Model Architecture - Multiple Output Node**

**One-Hot Encode the 'type'**


In [62]:
y_train.head()


5025    0
2238    0
4834    0
6143    0
2892    0
Name: type, dtype: int64

In [64]:
from keras.utils import to_categorical

# to_categorical will take Series and create a column for each possible value
y_train_cat = to_categorical(y_train)
y_test_cat = to_categorical(y_test)


(4352, 2)

In [65]:
pd.DataFrame(y_train_cat).head()

0    1
0  1.0  0.0
1  1.0  0.0
2  1.0  0.0
3  1.0  0.0
4  1.0  0.0

In [70]:
model = Sequential()

# Add the first layer
model.add(Dense(12, activation='relu', input_shape=(input_shape,)))

# Add the second layer
model.add(Dense(8, activation='relu'))

# Add the output layer
# NOTE - we specify 2 output layer nodes for each of the 0 or 1 outcomes
# We also use softmax to provide a probability across the two vales
model.add(Dense(2, activation='softmax'))

# compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [71]:
# fit will perform the backpropagation and gradient descent
# fit(X_train, y_train)
model.fit(X_train_scaled, y_train_cat, epochs=100, validation_split=0.4, batch_size=64, verbose=0)

In [72]:
score = model.evaluate(X_test_scaled, y_test_cat,verbose=1)
print(f'Loss: {score[0]}, Accuracy: {score[1]}')

68/68 [==============================] - 0s 1ms/step - loss: 0.0166 - accuracy: 0.9972
Loss: 0.016631925478577614, Accuracy: 0.9972028136253357


**Making predictions on multiple output node layer**

In [73]:
y_pred_proba = model.predict(X_test_scaled)

In [76]:
y_pred_proba[:,1]


array([1.67664723e-04, 9.98912811e-01, 2.83258036e-04, ...,
       9.99992371e-01, 1.03543965e-08, 3.04368295e-04], dtype=float32)

In [85]:
y_pred = y_pred_proba[:, 1] > 0.5
y_pred

array([False,  True, False, ...,  True, False, False])

In [86]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score, classification_report, accuracy_score


In [87]:
cm = confusion_matrix(y_test, y_pred)
# for this, lets assume any probability above 0.5, means Red wine
cm = confusion_matrix(y_test, y_pred >= 0.5)
df_cm = pd.DataFrame(
        cm, index=['white', 'red'], columns=['white', 'red'], 
    )
df_cm.head()

white  red
white   1615    2
red        4  524

In [88]:
precision_score(y_test, y_pred)

0.9961977186311787

In [89]:
recall_score(y_test, y_pred)

0.9924242424242424

In [90]:
f1_score(y_test,y_pred)


0.9943074003795065

In [91]:
cohen_kappa_score(y_test, y_pred)


0.9924532683153373

In [92]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1617
           1       1.00      0.99      0.99       528

    accuracy                           1.00      2145
   macro avg       1.00      1.00      1.00      2145
weighted avg       1.00      1.00      1.00      2145



**Create Model to predict Wine Quality - Regression**


In [93]:
df.head()

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  type
0            7.4              0.70         0.00  ...      9.4        5     1
1            7.8              0.88         0.00  ...      9.8        5     1
2            7.8              0.76         0.04  ...      9.8        5     1
3           11.2              0.28         0.56  ...      9.8        6     1
4            7.4              0.70         0.00  ...      9.4        5     1

[5 rows x 13 columns]

In [94]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3, 9])

In [95]:
X = df.drop(columns=['quality'])
y = df['quality']

In [97]:
imput_dim = X.shape[1]  # get the number of columns/features in X
imput_dim

12

**Create the hold-out set with train_test_split¶**

In [98]:
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42, stratify=y)

In [99]:
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [100]:
scaler = StandardScaler()

In [104]:
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

**Create a Keras Model as a Scikit-Learn Estimator**

In [105]:
from keras.wrappers.scikit_learn import KerasClassifier

In [106]:
def create_keras_wine_quality_model():
    # Initialize the model
    model = Sequential()

    # Add input layer 
    model.add(Dense(64, input_dim=imput_dim, activation='relu'))

    # Add output layer 
    model.add(Dense(1))
    
    model.compile(optimizer='rmsprop', loss='mean_squared_error', metrics=['mae'])
    
    return model

In [107]:
# Create a KerasRegressor that has a compatible API for Scikit-Learn estimator
estimator = KerasRegressor(build_fn=create_keras_wine_quality_model, epochs=100, batch_size=5, verbose=0)

In [109]:
kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=43)

In [110]:
results = cross_val_score(estimator, X_train_scaled, y_train, cv=kfold)

In [112]:
# The results are the mean_absolute_error which represent the number of 'units' off the measurements are
# https://github.com/scikit-learn/scikit-learn/issues/2439
# there is a super long debate about why Scikit learn cross_val_score returns negative mean absolute error values
# for now.. you can just flip the sign
results


array([-0.50535077, -0.46893468, -0.52781159])

In [111]:
print("Results: %.2f MSE (%.2f) STD" % (results.mean(), results.std()))

Results: -0.50 MSE (0.02) STD


**Create a model and fit it to the training data¶**

In [113]:
model = create_keras_wine_quality_model()
model.fit(X_train_scaled, y_train, epochs=100, validation_split=0.4, batch_size=64, verbose=0)

**Evaluate the model on the hold-out test set**

In [114]:
mse_value, mae_value = model.evaluate(X_test_scaled, y_test, verbose=0)

In [115]:
print(mse_value, mae_value)

0.5043332576751709 0.5531765222549438


You can see the hold-out has similar mean absolute error as the training data.



In [116]:
from sklearn.metrics import r2_score
y_pred = model.predict(X_test_scaled)
r2_score(y_test, y_pred)

0.3368542521283785

The R^2 score is also not very good. R^2 score of 1 is the best, and the score can go negative.

Therefore a score of 0.33 is not a very good score

In [ ]:
The R^2 score is also not very good. R^2 score of 1 is the best, and the score can go negative.

Therefore a score of 0.33 is not a very good score

**Create a Scikit-Learn Model Sandbox¶**

In [117]:
from keras.optimizers import SGD, RMSprop

def create_keras_wine_quality_deep_model():
    # Initialize the model
    model = Sequential()

    # Add input layer 
    model.add(Dense(128, input_dim=imput_dim, activation='relu'))

    # Add input layer 
    model.add(Dense(64, activation='relu'))

    # Add output layer 
    model.add(Dense(1))
    
    # rmsprop
    # RMSprop(lr=0.001)
    # SGD(lr=0.1)
    model.compile(optimizer=SGD(lr=0.001), loss='mean_squared_error', metrics=['mae'])
    
    return model

In [118]:
model = create_keras_wine_quality_deep_model()
model.fit(X_train_scaled, y_train, epochs=100, validation_split=0.4, batch_size=64, verbose=0)

In [119]:
se_value, mae_value = model.evaluate(X_test_scaled, y_test, verbose=0)
print(mse_value, mae_value)
y_pred = model.predict(X_test_scaled)
print(r2_score(y_test, y_pred))

0.5043332576751709 0.5770038962364197
0.27338636349341716


**Create model to predict Wine Quality - Classification¶**

In [121]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score, classification_report, accuracy_score
from keras.models import Sequential
from keras.layers import Dense

df_red = pd.read_csv('/content/winequality-red.csv', sep=';')
df_white = pd.read_csv('/content/winequality-white.csv', sep=';')

df_red['type'] = 1
df_white['type'] = 0

df = pd.concat([df_red, df_white], ignore_index=True)

X = df.drop(columns=['quality'])
y = df['quality']

In [142]:
print(y.unique())


[5 6 7 4 8 3 9]


In [143]:
# lets assume that wine quality with a value of 7 or greater is considered good wine.  With a target value of 1
y = y >= 7

In [146]:
#spliting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, stratify=y)

scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
input_shape = X_train.shape[1]

y_train_cat = to_categorical(y_train)
y_test_cat = to_categorical(y_test)


In [147]:
model = Sequential()

# Add the first layer
model.add(Dense(128, activation='relu', input_shape=(input_shape,)))

# Add the second layer
model.add(Dense(64, activation='relu'))

# Add the output layer
# NOTE - we specify 2 output layer nodes for each of the 0 or 1 outcomes
# We also use softmax to provide a probability across the two vales
model.add(Dense(2, activation='softmax'))

# compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train_scaled, y_train_cat, epochs=1000, validation_split=0.4, batch_size=64, verbose=0)


In [160]:
y_pred = y_pred_proba[:, 1] > 0.5

cm = confusion_matrix(y_test, y_pred)
# for this, lets assume any probability above 0.5, means Red wine
cm = confusion_matrix(y_test, y_pred >= 0.5)
df_cm = pd.DataFrame(
        cm, index=['Bad', 'Good'], columns=['Bad', 'Good'], 
    )
print(df_cm.head())

print(f'Accuracy: {accuracy_score(y_test, y_pred)}')

       Bad  Good
Bad   1313   410
Good   306   116
Accuracy: 0.6662004662004662


**Create Scikit-Learn MLP Model to predict Wine Quality¶**

In [162]:
from sklearn.neural_network import MLPClassifier
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score, classification_report, accuracy_score


df_red = pd.read_csv('/content/winequality-red.csv', sep=';')
df_white = pd.read_csv('/content/winequality-white.csv', sep=';')

df_red['type'] = 1
df_white['type'] = 0

df = pd.concat([df_red, df_white], ignore_index=True)

X = df.drop(columns=['quality'])
y = df['quality']

# lets assume that wine quality with a value of 7 or greater is considered good wine.  With a target value of 1
y = y >= 7

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, stratify=y)

scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
input_shape = X_train.shape[1]

y_train_cat = to_categorical(y_train)
y_test_cat = to_categorical(y_test)

# create a Input ->128 Node Hidden Layer -> 64 Node Hidden Layer -> Output
# equivalent Keras:  128, 64 = 0.851 accuracy
# 128, 64, 16 = 0.862 accuracy
# 128, 64, 16, 8 = 0.863 accuracy
model = MLPClassifier(solver='adam', alpha=1e-5, max_iter=1000,
                    hidden_layer_sizes=(128, 64, 16, 8), random_state=1)
print(model)

model.fit(X_train_scaled, y_train_cat)

y_pred_proba = model.predict(X_test_scaled)

y_pred = y_pred_proba[:, 1]

cm = confusion_matrix(y_test, y_pred)
# for this, lets assume any probability above 0.5, means Red wine
cm = confusion_matrix(y_test, y_pred >= 0.5)
df_cm = pd.DataFrame(
        cm, index=['Bad', 'Good'], columns=['Bad', 'Good'], 
    )
print(df_cm.head())

print(f'Accuracy: {accuracy_score(y_test, y_pred)}')

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(128, 64, 16, 8), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)
       Bad  Good
Bad   1610   113
Good   181   241
Accuracy: 0.862937062937063
